---

  plugins:
    - jest
    - babel

  env:
    example/custom: true
    node: true
    jest: true
    

  parser: babel-eslint


  plugins:
    - 'airbnb-base'
    - 'plugin:jest/recommended'
    - 'plugin:lodash-fp/recommended'

  rules:
  no-console: 0

